#!/bin/sh

### BEGIN INIT INFO
# Provides: gyah3c-daemon
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start Daemon of GYaH3C
# Description: Start Daemon of GYaH3C, privide dbus support
### END INIT INFO

PATH_TO_PYTHON=/usr/bin/python

case "$1" in
    start)
        /usr/bin/gyah3c-daemon start
        ;;
    stop)
        /usr/bin/gyah3c-daemon stop
        ;;
    restart)
        /usr/bin/gyah3c-daemon restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
