#!/bin/sh

case "$1" in
    start)
        /usr/bin/gyah3c-daemon
        ;;
    stop)
        kill `ps -ef | grep gyah3c-daemon | awk '{print $2}'`
        ;;
    restart|reload)
        $0 stop
        $1 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
esac
